/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'on-primary-fixed-variant': '#6b3b00',
        'tertiary-container': '#b89aff',
        'surface-bright': '#31394d',
        'on-secondary-fixed-variant': '#004f54',
        'error': '#ffb4ab',
        'tertiary': '#d1bcff',
        'on-surface': '#dae2fd',
        'surface-container': '#171f33',
        'on-background': '#dae2fd',
        'surface-container-low': '#131b2e',
        'surface-container-highest': '#2d3449',
        'surface-dim': '#0b1326',
        'inverse-surface': '#dae2fd',
        'on-tertiary-container': '#4e00b6',
        'on-primary-fixed': '#2d1600',
        'inverse-on-surface': '#283044',
        'outline-variant': '#554335',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#7df4ff',
        'on-secondary-fixed': '#002022',
        'secondary-fixed-dim': '#00dbe9',
        'error-container': '#93000a',
        'surface-tint': '#ffb874',
        'outline': '#a38d7b',
        'on-tertiary': '#3c0090',
        'on-secondary': '#00363a',
        'on-tertiary-fixed-variant': '#5700c9',
        'tertiary-fixed-dim': '#d1bcff',
        'secondary': '#d3fbff',
        'on-secondary-container': '#00686f',
        'surface-variant': '#2d3449',
        'surface-container-lowest': '#060e20',
        'surface-container-high': '#222a3d',
        'secondary-container': '#00eefc',
        'primary-fixed': '#ffdcbf',
        'background': '#0b1326',
        'inverse-primary': '#8c4f00',
        'tertiary-fixed': '#e9ddff',
        'on-surface-variant': '#dbc2ae',
        'on-primary': '#4b2800',
        'on-primary-container': '#603500',
        'primary': '#ffb874',
        'on-tertiary-fixed': '#23005b',
        'surface': '#0b1326',
        'primary-fixed-dim': '#ffb874',
        'primary-container': '#f7931a',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'xl': '64px',
        'sm': '16px',
        'md': '24px',
        'gutter': '24px',
        'lg': '40px',
        'base': '4px',
        'xs': '8px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
